### ISSUE TITLE
fbcvsubset_mgiribbons seems to be slighly accidentally formatted (would not work in the fbcv.obo)

### ISSUE THREAD

**Issue by matentzn** [FlyBase/drosophila-phenotype-ontology#1]
```
Declaration(AnnotationProperty(:fbcvsubset_mgiribbons))
Declaration(AnnotationProperty(fbcv:BRAIN_NAME_ABV))
Declaration(AnnotationProperty(fbcv:BRAND_NAME))
```

I am wondering whether i can change that to:

```
Declaration(AnnotationProperty(fbcv:subset_mgiribbons))
Declaration(AnnotationProperty(fbcv:BRAIN_NAME_ABV))
Declaration(AnnotationProperty(fbcv:BRAND_NAME))
```

And, of course, fix all other references in the file as well. Note that : is the default namespace, which is ontology iri, so in this here case purl/dpo.owl, so this may not what you want (because you want this to work with fbcv.obo).

**Comment by matentzn** [comment]
@dosumis

**Comment by dosumis** [comment]
Check if actually used in FBcv once imported terms are flushed.  If so keep and fix as above.  

This is, of course, another example of why subset IRIs really are a bloody mess.  They only make sense if use is restricted to short_forms - but this makes for a high probability of namespace clashes in integrative projects like Monarch & AGR.  Perhaps worth putting together am OBO foundry ticket on this?

**Comment by matentzn** [comment]
Check this: https://github.com/FlyBase/flybase-controlled-vocabulary/blob/53d26bed4fe66af62811616bda65c49ddebfcdc5/releases/fbcv.obo#L19

They appear to be used.

**Comment by matentzn** [comment]
This has since been fixed
