### ISSUE TITLE
Slightly risky line of code: can someone fix?

### ISSUE THREAD

**Issue by matentzn** [FlyBase/drosophila-phenotype-ontology#10]
There is a risky use of sed [here](https://github.com/FlyBase/drosophila-phenotype-ontology/blob/620a4865b2e2e25e5a139110a93abb5dbd9a2473/src/ontology/dpo.Makefile#L159).

It is currently saying:
```
sed -i '/sub_/d' ./dpo-edit-release.owl
```

it should say:

```
sed -i '/$sub_/d' ./dpo-edit-release.owl
```

But cant get it to work. @dosumis

**Comment by Clare72** [comment]
this is one of the things I replaced with 'grep -v' as it is just deleting lines, so no longer an issue
