### ISSUE TITLE
phenotypes for increased/decreased memory

### ISSUE THREAD

**Issue by Clare72** [FlyBase/drosophila-phenotype-ontology#102]
Definition of 'memory' in GO:
>The activities involved in the mental information processing system that receives (registers), modifies, stores, and retrieves informational stimuli. The main stages involved in the formation and retrieval of memory are encoding (processing of received information by acquisition), storage (building a permanent record of received information as a result of consolidation) and retrieval (calling back the stored information and use it in a suitable way to execute a given task).

It is not usually clear which parts of this are better or worse when a memory phenotype is observed.
What is measured is usually the retrieval (% of a population exhibiting expected behavior), but retrieval may not be where the problem lies and none of this really fits rate (which is a defined as occurrence/time).

'rate' in PATO:
>A quality of a single process inhering in a bearer by virtue of the bearer's occurrence per unit time.

'efficacy' - PATO:0015002 may be better for memory
>The ability of a process to produce its output.

**Comment by Clare72** [comment]
@arzuozturk @vmt25 @gm119 
We now have patterns for increased/decreased efficacy of behavior, so the next step of actually making the phenotypes will be easy. Did you want increased/decreased for all the new subclasses (LTM, STM, etc) or just the parent 'memory' phenotype?

**Comment by arzuozturk** [comment]
I think it would be great if we can have increased/decreased for all new memory term subclasses.
