### ISSUE TITLE
minor inconsistencies in the fertile-sterile FBcv term definitions

### ISSUE THREAD

**Issue by arzuozturk** [FlyBase/drosophila-phenotype-ontology#108]
**Issues**
1. Are "fertilized eggs", "zygote" and "fertilized offspring" being used redundantly? If yes, would it be possible to stick to one for the sake of consistency? Or at least keep it consistent between a parent term (g) and its children (h and i)?

2. "ability to mate" in some of the fertile-sterile terms (a, b, c, h and i) is confusing. We already have abnormal mating behavior (FBcv_0000721) to capture mating defects. Could we remove the 'ability to mate" statement from those definitions?

**fertile-sterile terms**
a) fertile (FBcv_0000374): A phenotype that is the ability to mate and as a result produce fertilized eggs.
b) male fertile (FBcv_0000376): A phenotype that is the ability of males to mate and as a result produce fertilized eggs.
c) female fertile (FBcv_0000377): A phenotype that is the ability of females to mate and as a result produce fertilized eggs.

d) semi-fertile (FBcv_0000375): Phenotype that is a reduction in the proportion of fertilized eggs produced, but only to > 50% of wild-type.
e) male semi-fertile (FBcv_0000006): Phenotype of males that is a reduction in the proportion of fertilized eggs produced, but only to > 50% of wild-type.
f) female semi-fertile (FBcv_0000007): Phenotype of females that is a reduction in the proportion of fertilized eggs produced, but only to > 50% of wild-type.

g) sterile (FBcv_0000364): A phenotype that is the inability to produce a zygote.
h) male sterile (FBcv_0000370): A phenotype that is the inability of males to mate and produce fertilized offspring.
i) female sterile (FBcv_0000366): A phenotype that is the inability of females to mate and produce fertilized offspring.

j) semi-sterile (FBcv_0000365): A phenotype that is a reduction in the proportion of fertilized eggs produced to below 50% of wild-type.
k) male semi-sterile (FBcv_0000371): A phenotype that is a reduction in the proportion of fertilized eggs produced by males to below 50% of wild-type.
l) female semi-sterile (FBcv_0000367): A phenotype that is a reduction in the proportion of fertilized eggs produced by females to below 50% of wild-type.

**Comment by Clare72** [comment]
>do you think it would be a good idea to add definitions to the anatomy terms “egg", "unfertilized egg" and "fertilized egg"?

probably, but that should be a separate ticket on the FBbt repo.
