### ISSUE TITLE
Add xrefs of classes that were source for the definition to the definition?

### ISSUE THREAD

**Issue by matentzn** [FlyBase/drosophila-phenotype-ontology#16]
For example:

X as defined_by $sub_GO:001 previously got an xref to GO:001 on top of any already existing xrefs. @Clare72 let me know whether this is priority for this release.

**Comment by Clare72** [comment]
Yes, I can see that these have gone, I don't think it is a big deal since GO ids are included in the definition text. Would be nice to restore them at some point, but not a priority.

**Comment by matentzn** [comment]
I think there used to be dbxrefs to the original authors:

```
Annotation(<http://www.geneontology.org/formats/oboInOwl#hasDbXref> "GOC:jid"^^xsd:string)
```

Is this what we want, or an xref to the GO term?

```
Annotation(<http://www.geneontology.org/formats/oboInOwl#hasDbXref> "GO:001"^^xsd:string)
```

**Comment by matentzn** [comment]
This is fixed now.
