### ISSUE TITLE
We should move `developmental rate defective` to the abnormalProcess pattern

### ISSUE THREAD

**Issue by matentzn** [FlyBase/drosophila-phenotype-ontology#22]
https://www.ebi.ac.uk/ols/ontologies/dpo/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FFBcv_0000450

(remove the stage ref)

**Comment by Clare72** [comment]
Problem is that GO 'developmental process' covers a lot of things that could happen in the adult, but we only want 'developmental rate' to apply during development (before adult)

https://www.ebi.ac.uk/ols/ontologies/go/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGO_0032502

**Comment by matentzn** [comment]
That is a question for @dosumis! We have started to introduce patterns that involve stage restrictions; but these should be carefully considered..

**Comment by dosumis** [comment]
The stage restriction here is what the FB curator said reflected intent and usage.  The relation used for is should be good, so I think it's OK.

**Comment by matentzn** [comment]
I think then @Clare72 you can close this issue here but request a new pattern in the upheno repo (also mention this ticket here for context). Maybe something like "abnormal rate of development before stage". 

This does however open us up to the risks of open vs. closed world - in particular, how does this differ from "abnormal rate of development" - the latter describes an abnormal rate during any stage (include pre-adult), while the latter -> means that the development post adult is unknown? is normal? Doesn't this belong in the metadata in this case (stage in which the phenotype was determined?). I am just speaking aloud here for when people ask: why do we need this pattern.

**Comment by dosumis** [comment]
I think we just consider pre-adult developmental processes as a straightforward subclass of developmental process.  I don't see any open vs closed world issues.  The problems for OWL modelling come when we start talking about stages of continuants.

**Comment by matentzn** [comment]
OK! So the increasedRateOfBiologicalProcessDuringStage is simply defined as:

```
description: "Increased rate of a biological process, i.e. increased number of events per unit time of a biological process, or increased output of a continuous biological process) during a particular stage."
```

Sounds ok to me; still wondering in general whether we should really have measurement time points slip into our patterns. It is just not clear to me whether this stage here is an experimental conditation that belongs in the annotations or an inherent property of the phenotype, which belongs in the EQ; but ok. Since we opened that box, why not continue and see how it pans out..

**Comment by dosumis** [comment]
Why is it an experimental condition?  Different (dev) processes happen at different stages - whether or not an expt is taking place.

**Comment by Clare72** [comment]
>It is just not clear to me whether this stage here is an experimental conditation that belongs in the annotations or an inherent property of the phenotype, which belongs in the EQ

It is the latter. In this case we consider 'development' to occur as the animal passes through embryonic/larval/pupal stages, with 'development' ending with the generation of the mature adult fly.

It might be better to have a GO term for 'pre-adult developmental process', rather than using ('developmental process' and ('preceded by' some 'mature adult stage')), but not sure if they would be willing to make that(?)
