### ISSUE TITLE
dpoIItowards.tsv instances should be moved to abnormallyIncreasedNumberOfAnatomicalEntity

### ISSUE THREAD

**Issue by matentzn** [FlyBase/drosophila-phenotype-ontology#23]
https://github.com/obophenotype/upheno/blob/master/src/patterns/dosdp-dev/abnormallyIncreasedNumberOfAnatomicalEntity.yaml

**Comment by matentzn** [comment]
(and abnormal/decreased number; careful which you assign :) 

https://github.com/FlyBase/drosophila-phenotype-ontology/blob/master/src/patterns/data/original/dpoIItowards.tsv

**Comment by Clare72** [comment]
These were abnormal, increased and decreased cell number - now patternised
see #37
