### ISSUE TITLE
Manual review of dpo.owl and dpo.obo required

### ISSUE THREAD

**Issue by matentzn** [FlyBase/drosophila-phenotype-ontology#3]
We need some basic looking at (sanity checking, does it look mostly normal?) and diffing of dpo.obo (and .owl) with previous releases! The only thing that is missing is the definition generator. Working on that!

**Comment by matentzn** [comment]
@Clare72 I finished the full dpo release. I think a five minute action comparing 

https://raw.githubusercontent.com/FlyBase/flybase-controlled-vocabulary/master/releases/dpo-simple.obo

with 

https://raw.githubusercontent.com/FlyBase/drosophila-phenotype-ontology/master/dpo-simple.obo

should be fine. No more than 10 mins. If you are happy for now, you can close this issue and make a new ticket on this repo: "Create first official github release and change purl config" and assign it to me. Merci!

**Comment by Clare72** [comment]
This all looks fine to me.
