### ISSUE TITLE
Add dosumis as contributor to repo

### ISSUE THREAD

**Issue by matentzn** [FlyBase/drosophila-phenotype-ontology#42]
So we can assign tickets to him ;P

**Comment by Clare72** [comment]
Did this a while ago...

<img width="784" alt="Screenshot 2019-09-22 at 17 09 30" src="https://user-images.githubusercontent.com/38460997/65394415-5f3d1580-dd7d-11e9-84f7-4ffab5ccc94c.png">

**Comment by matentzn** [comment]
Will nag him to accept.

**Comment by matentzn** [comment]
Thx :P
