### ISSUE TITLE
Restrictions on aplastic/hypoplastic definition inconsistent with PATO worldview.

### ISSUE THREAD

**Issue by matentzn** [FlyBase/drosophila-phenotype-ontology#52]
It boils down to this:

aplastic, a subclass of aplastic/hypoplastic, is defined in PATO as the intersection of agenesis and aplastic/hypoplastic. agensis explicitly implies "absent". Unfortunately, DPO (FBCV) asserts that aplastic/hypoplastic is a subclass of "decreased size", which, via a trail of complicated expressions, implies "present". Since present and absent are disjoint, aplastic becomes unsatisfiable (inconsistent).

An easy way to fix this would be to remove the assertion that aplastic/hypoplastic is a subclass of decreased size. It is up to you. Is this something you would be willing to fix? It would help me in my agenda to unify phenotype pattern design across species.

**Comment by Clare72** [comment]
PATO imports are now updated - issue is solved
